
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pip install pyinstaller
    - pyinstaller main.py
    - salt -L "porchcam, eastgaragecam" state.sls deploy
    - salt -L "porchcam, eastgaragecam" service.restart camera