image: "python:3.8"
before_script:
  - pip install pyinstaller
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - pyinstaller main.py
    - salt -L "porchcam, eastgaragecam" state.sls deploy
    - salt -L "porchcam, eastgaragecam" service.restart camera