stages:
  - deploy
  - validate

deploy:
  stage: deploy
  script:
    - salt -L 'porchcam, eastgaragecam' cmd.run 'cd /home/pi/FFStreamerCapture; git reset --hard; git pull'
validate:
  stage: validate
  script:
    - salt -L 'porchcam, eastgaragecam' service.status camera'