before_script:
  - pip3 install pyinstaller
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pip3 install -r requirements.txt
    - pyinstaller main.py
    - salt -L "porchcam, eastgaragecam" state.sls deploy
    - salt -L "porchcam, eastgaragecam" service.restart camera